export const text1: string  = "This website resolves around a concept called Fantasy Premier League (FPL), a popular online game where you select and manage a virtual team of football players playing in the English Premier League. The goal of the game is to get as many points as possible throughout the season, where points are awarded based on some predefined metrics of how the players in your virtual team are performing in real life. A season consists of 38 rounds, or gameweeks as they are called in FPL. For each gameweek, there will always be a team with the highest possible score for that gameweek, and the purpose of this site is to predict these 'dream teams' for every gameweek."

export const text2: string  = "The dream team predictions are based on a supervised machine learning model called Neural Network. This model has learned to predict individual player scores by processing data on the last four seasons of FPL, and the score predictions are primarily based on selected performance metrics from the last three gameweeks for each player.  Moreover, the model consists of four sub-models, each specialized on one of the four player positions that exist in FPL. The data used to train the model is available through the official FPL API."

export const text3: string  = "The teams are selected using an optimization algorithm called Simplex. This algorithm optimizes the team in a locked 3-4-3 formation based on the model predictions. The team values is limited at 83 million, and all other team constraints that exist in FPL are also considered by this algorithm. Furthermore, each team has a captain and a vice-captain, and these are selected based on the two highest score predictions."

export const text4: string  = "In order to evaluate the performance of the dream teams, their scores are compared to the scores of the Scout Selection teams. These teams are made prior to every gameweek by the official expert panel of FPL, and they follow the exact same constrains. For gameweek 4 to gameweek 9 this season, the Scout Selection teams have a cumulative score of 326 points, which would place them roughly among the top 27% in FPL. In comparison, the dream teams on this site have a cumulative score of 383 points. This would roughly be awarded with a place among the top 2%, which is significantly better than the Scout Selection teams. One important note here is that both the dream teams and the Scout Selection teams operate with slightly different constraints than the rest of the teams in FPL, so the placements mentioned are not exact. "

export const text5: string  = "This website will be updated continuously in the future as improvements are made. One improvement would be to improve the prediction model by providing more data, like xG, odds and other more subtle metrics, as well as improving the model itself. Other improvements include extensions like incorporating the concepts of player transfers and chips in FPL into the model. The ultimate ambition of this website is to create a computer program that can master every concept and nuance of FPL and eventually play the game itself and beat the rest of the world."
